CREATE TABLE IF NOT EXISTS clients (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	host VARCHAR(255) NOT NULL,
	port INTEGER NOT NULL,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	ssl BOOLEAN NOT NULL DEFAULT false,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

