name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: [self-hosted, arm64]
    steps:
    - uses: actions/checkout@v5
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.7.2
    
  build:
    runs-on: [self-hosted, arm64]
    needs: lint
    steps:
    - uses: actions/checkout@v5

    - name: Build
      run: go build -v ./...
